# Generated by Django 5.2 on 2025-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
